{
  "id": "CVE-2023-41105",
  "description": "An issue was discovered in Python 3.11 through 3.11.4. If a path containing '\\0' bytes is passed to os.path.normpath(), the path will be truncated unexpectedly at the first '\\0' byte. There are plausible cases in which an application would have rejected a filename for security reasons in Python 3.10.x or earlier, but that filename is no longer rejected in Python 3.11.x.",
  "scope": "local",
  "packages": [
    {
      "name": "python3.7",
      "status": "resolved",
      "urgency": "unimportant",
      "fixed_version": "0",
      "repository": [
        {
          "name": "buster",
          "version": "3.7.3-2+deb10u3"
        },
        {
          "name": "buster-security",
          "version": "3.7.3-2+deb10u6"
        }
      ]
    },
    {
      "name": "python2.7",
      "status": "resolved",
      "urgency": "unimportant",
      "fixed_version": "0",
      "repository": [
        {
          "name": "buster",
          "version": "2.7.16-2+deb10u1"
        },
        {
          "name": "buster-security",
          "version": "2.7.16-2+deb10u3"
        }
      ]
    }
  ]
}
