{
	"id": "CVE-2022-45061",
	"description": "An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16.",
	"scope": "local",
	"packages": [
		{
			"name": "python3.7",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3.7.3-2+deb10u5",
			"repository": [
				{
					"name": "buster-security",
					"version": "3.7.3-2+deb10u6"
				},
				{
					"name": "buster",
					"version": "3.7.3-2+deb10u3"
				}
			]
		},
		{
			"name": "python2.7",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "2.7.16-2+deb10u2",
			"repository": [
				{
					"name": "buster",
					"version": "2.7.16-2+deb10u1"
				},
				{
					"name": "buster-security",
					"version": "2.7.16-2+deb10u3"
				}
			]
		}
	]
}
