{
  "id": "CVE-2017-5992",
  "description": "Openpyxl 2.4.1 resolves external entities by default, which allows remote attackers to conduct XXE attacks via a crafted .xlsx document.",
  "debian_bug": 854442,
  "scope": "local",
  "packages": [
    {
      "name": "openpyxl",
      "status": "resolved",
      "urgency": "not yet assigned",
      "fixed_version": "2.3.0-3",
      "repository": [
        {
          "name": "buster",
          "version": "2.4.9-1"
        }
      ]
    }
  ]
}
