{
	"id": "CVE-2019-18874",
	"description": "psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object.",
	"debian_bug": 944605,
	"scope": "local",
	"packages": [
		{
			"name": "python-psutil",
			"status": "resolved",
			"urgency": "low",
			"fixed_version": "5.6.7-1",
			"repository": [
				{
					"name": "trixie",
					"version": "5.9.8-1"
				}
			]
		}
	]
}
