{
	"id": "CVE-2024-41990",
	"description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
	"debian_bug": 1078074,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3:4.2.15-1",
			"repository": [
				{
					"name": "sid",
					"version": "3:4.2.15-1"
				}
			]
		}
	]
}
