{
	"id": "CVE-2012-3444",
	"description": "The get_image_dimensions function in the image-handling functionality in Django before 1.3.2 and 1.4.x before 1.4.1 uses a constant chunk size in all attempts to determine dimensions, which allows remote attackers to cause a denial of service (process or thread consumption) via a large TIFF image.",
	"debian_bug": 683364,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "1.4.1-1",
			"repository": [
				{
					"name": "sid",
					"version": "3:4.2.13-1"
				}
			]
		}
	]
}
