{
	"id": "CVE-2020-24583",
	"description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
	"debian_bug": 969367,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "2:2.2.16-1",
			"repository": [
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u5"
				},
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				}
			]
		}
	]
}
