{
	"id": "CVE-2020-14422",
	"description": "Lib/ipaddress.py in Python through 3.8.3 improperly computes hash values in the IPv4Interface and IPv6Interface classes, which might allow a remote attacker to cause a denial of service if an application is affected by the performance of a dictionary containing IPv4Interface or IPv6Interface objects, and this attacker can cause many dictionary entries to be created. This is fixed in: v3.5.10, v3.5.10rc1; v3.6.12; v3.7.9; v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1; v3.9.0, v3.9.0b4, v3.9.0b5, v3.9.0rc1, v3.9.0rc2.",
	"scope": "local",
	"packages": [
		{
			"name": "python2.7",
			"status": "resolved",
			"urgency": "unimportant",
			"fixed_version": "0",
			"repository": [
				{
					"name": "bullseye",
					"version": "2.7.18-8+deb11u1"
				}
			]
		},
		{
			"name": "python-ipaddress",
			"status": "open",
			"nodsa": "Minor issue",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "bullseye",
					"version": "1.0.23-1"
				}
			]
		}
	]
}
