{
	"id": "CVE-2023-52323",
	"debian_bug": 1060059,
	"packages": [
		{
			"name": "pycryptodome",
			"status": "open",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "sid",
					"version": "3.18.0+dfsg1-1"
				}
			]
		}
	]
}
