{
	"id": "CVE-2018-11499",
	"description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
	"debian_bug": 900182,
	"scope": "local",
	"packages": [
		{
			"name": "libsass",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3.5.5-3",
			"repository": [
				{
					"name": "buster",
					"version": "3.5.5-4"
				}
			]
		}
	]
}
