{
  "id": "CVE-2020-27545",
  "description": "libdwarf before 20201017 has a one-byte out-of-bounds read because of an invalid pointer dereference via an invalid line table in a crafted object.",
  "scope": "local",
  "packages": [
    {
      "name": "dwarfutils",
      "status": "open",
      "nodsa": "Minor issue",
      "nodsa_reason": "ignored",
      "urgency": "not yet assigned",
      "repository": [
        {
          "name": "buster",
          "version": "20180809-1"
        }
      ]
    }
  ]
}
