{
  "id": "CVE-2021-32492",
  "description": "A flaw was found in djvulibre-3.5.28 and earlier. An out of bounds read in function DJVU::DataPool::has_data() via crafted djvu file may lead to application crash and other consequences.",
  "scope": "local",
  "packages": [
    {
      "name": "djvulibre",
      "status": "resolved",
      "urgency": "not yet assigned",
      "fixed_version": "3.5.27.1-10+deb10u1",
      "repository": [
        {
          "name": "buster-security",
          "version": "3.5.27.1-10+deb10u1"
        },
        {
          "name": "buster",
          "version": "3.5.27.1-10+deb10u1"
        }
      ]
    }
  ]
}
