{
	"id": "CVE-2024-39329",
	"description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password.",
	"debian_bug": 1076069,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "open",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u2"
				},
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				}
			]
		}
	]
}
